export const AsyncStatus = {
  IDLE: 'IDLE',
  REQUEST: 'REQUEST',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED'
}

export const AuthActions = {
  AUTH_USER_AUTHENTICATE: 'AUTH_USER_AUTHENTICATE',
  AUTH_USER_LOGOUT: 'AUTH_USER_LOGOUT',
  AUTH_CHECK_TOKEN: 'AUTH_CHECK_TOKEN'
}
